### ISSUE TITLE
 [gzserver] Sleep time is larger than clock resolution, skipping sleep

### ISSUE THREAD

**Issue by liesrock** [ADVRHumanoids/rosee_gazebo_plugins#3]
During the execution of the simulation with the rosee_gazebo_plugin I repeatedly receive the following warning inside gzserver:

```
[Wrn] [Time.cc:449] Sleep time is larger than clock resolution, skipping sleep
```

I did not figure out why, but the simulation is correctly working (fyi @torydebra ).

I will try to investigate more.

**Comment by liesrock** [comment]
I am using Gazebo 8.6.0

**Comment by torydebra** [comment]
Now that I am trying gazebo 8 for other projects, I have errors.
How is it possible that you do not have errors, but only that warn (that is not present for me even with gazebo 8, anyway)

I have the following errors with gazebo8:
~~~
[Err] [Plugin.hh:180] Failed to load plugin libRoseePlugin.so: libgazebo_physics.so.7: cannot open shared object file: No such file or directory
~~~
this because the rosee_gazebo_plugin relies on 7 version...

Also the mimic plugin relies on the 7 version, and gives error:
~~~
[Err] [Plugin.hh:180] Failed to load plugin libroboticsgroup_gazebo_mimic_joint_plugin.so: libgazebo_physics.so.7: cannot open shared object file: No such file or directory
~~~

**Comment by liesrock** [comment]
Did you recompile your plugin after the installation of Gazebo 8 and its related dev?

**Comment by torydebra** [comment]
> Did you recompile your plugin after the installation of Gazebo 8 and its related dev?

Right, I solved after recompiling. Also mimic joint plugin work flawlessy.

Anyway, I do not have the warn you reported in the first message. Gazebo 8.6.0, too.

But I raise with other warnings:
~~~
[Wrn] [GuiIface.cc:117] void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "&File" under id 56
[Wrn] [GuiIface.cc:117] void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "&Edit" under id 59
[Wrn] [GuiIface.cc:117] void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "&Camera" under id 61
[Wrn] [GuiIface.cc:117] void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "&View" under id 64
[Wrn] [GuiIface.cc:117] void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "&Window" under id 68
[Wrn] [GuiIface.cc:117] void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "&Help" under id 73
~~~
I do not think they are important, they happen also with other projects.

**Comment by liesrock** [comment]
Ok, so this warning is not there?

```
[Wrn] [Time.cc:449] Sleep time is larger than clock resolution, skipping sleep
```

**Comment by torydebra** [comment]
> Ok, so this warning is not there?
> 
> ```
> [Wrn] [Time.cc:449] Sleep time is larger than clock resolution, skipping sleep
> ```

Not on my system, with same gazebo version you have (8.6)

**Comment by liesrock** [comment]
To solve the issue I had to remove the "acpi=off" from Grub
